### ISSUE TITLE
Add gifs to Exercise class

### ISSUE THREAD

**Issue by cbrandt6** [CarlJoos/Workout#1]
Add support to the Exercise class for gifs. Should be displayed when viewing a single exercise.

**Comment by CarlJoos** [comment]
how on earth do gifs work in flutter

**Comment by cbrandt6** [comment]
Place your gif in your images folder of your project and mention it in pubspec.yaml file,just like you do for images.

Image.asset(
  "images/loading.gif",
  height: 125.0,
  width: 125.0,
),

https://stackoverflow.com/questions/51556356/how-to-display-animated-gif-in-flutter

**Comment by cbrandt6** [comment]
Closed in PR #4
